//
// Created by lsharabi on 02/12/16.
//

#ifndef MYPROJECTNAME_MANUFACTURER_H
#define MYPROJECTNAME_MANUFACTURER_H

enum Manufacturer{
    NOT_VALID_MANUFACTURER,
    HONDA,
    SUBARO,
    TESLA,
    FIAT
};

#endif //MYPROJECTNAME_MANUFACTURER_H
