//
// Created by lsharabi on 02/12/16.
//

#ifndef MYPROJECTNAME_MARTIALSTATUS_H
#define MYPROJECTNAME_MARTIALSTATUS_H


enum MartialStatus{
    SINGLE,
    MARRIED,
    DIVORCED,
    WIDDOWED
};
#endif //MYPROJECTNAME_MARTIALSTATUS_H
